[package]
name = "clir_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_colours = "1.2.2"
ansi_term = "0.12.1"
bytemuck = "1.15.0"
cgmath = "0.18.0"
image = "0.25.1"
